export const GET_CLIENTS = "GET_CLIENTS"
export const GET_CLIENTS_REQUESTED = 'GET_CLIENTS_REQUESTED'
export const GET_APPLICANTS = "GET_APPLICANTS"
export const GET_APPLICANTS_REQUESTED = 'GET_APPLICANTS_REQUESTED'
export const REMOVE_APPLICANTS = 'REMOVE_APPLICANTS'
export const SAVE_CLIENT_ID = 'SAVE_CLIENT_ID'
export const SAVE_APPLICANTS = 'SAVE_APPLICANTS'
export const ADD_NEW_APPLICANT = 'ADD_NEW_APPLICANT'
export const REMOVE_NEW_APPLICANT = 'REMOVE_NEW_APPLICANT'

